CREATE TABLE IF NOT EXISTS  LYRICS (
    ID uuid DEFAULT random_uuid() PRIMARY KEY,
    CODE VARCHAR(8),
    NAME VARCHAR(255),
    BOOK_NAME VARCHAR(255),
    BOOK_INDEX VARCHAR(10),
    PAGES JSON,
    NAME_LENGTH Int
    );


