openapi: '3.0.2'
info:
  title: Lyrics Slide Management
  version: '1.0'
servers:
  - url: http://localhost:8080

paths:
  /lyrics:
    get:
      description: 'getList'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LyricsListItem'
    post: 
      description: 'Create New'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LyricsCreateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReurestStatus'
  /lyrics/{id}:
    get:
      description: 'get Detail'
      parameters:
      - name: "id"
        in: "path"
        description: "Lyrics UUID"
        required: true
        schema:
          $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LyricsItemDetial'
    put:
      description: 'update Lyrics'
      parameters:
      - name: "id"
        in: "path"
        description: "Lyrics UUID"
        required: true
        schema:
          $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LyricsItemDetial'
  /lyrics/{id}/download:
    get:
      description: 'download PPTX file'
      parameters:
      - name: "id"
        in: "path"
        description: "Lyrics UUID"
        required: true
        schema:
          $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: Download PPTX file
          content:
            application/octet-stream: {}
        '404':
          description: Id not find in system
  /lyrics/import:
    get:
      responses:
        '200':
          description: Download Sample Import File
          content:
            application/octet-stream: {}
    post:
      requestBody:
        content:
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: 'completed'
components:
  schemas:
    Id:
      type: string
      format: uuid
      example: d290f1ee-6c54-4b01-90e6-d701748f0851
    ReurestStatus:
      type: object
      properties:
        status: 
          type: number
          example: 200
    LyricsCreateRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/LyricsItem'
        - $ref: '#/components/schemas/LyricsPages'      
    LyricsItem: 
      properties:
        name:
          type: string
          example: '我是主的羊'
        book:
          type: string
          example: '青年聖歌 III'
        index:
          type: string
          example: '43'
    LyricsListItem:
      type: object
      allOf:
        - $ref: '#/components/schemas/LyricsItem'
      properties:
        id:
          $ref: '#/components/schemas/Id'
      
    LyricsItemDetial:
      allOf:
        - $ref: '#/components/schemas/LyricsItem'
        - $ref: '#/components/schemas/LyricsPages'
    LyricsPages:
      properties:
        pages:
          type: array
          items:
            type: array
            items: 
              type: string
              example: ['主領我到青草地，安歇在溪水旁','黃昏時主與我一路同行，','牧場上主的羊都得飽足心快暢，我是主的羊。']
              
